### ISSUE TITLE
Don't recreate tags

### ISSUE THREAD

**Issue by mkroening** [rwthmoodle/Sync-my-L2P#14]
Recreating the same tag over and over again makes it hard to package this project, as the hash of the source code tarball changes each time, while the location stays the same, making it impossible to build the old version of the project until it is repackaged.

It would be great, if this project would have new releases created without having old releases removed. Bumping the version number on each change to the binaries would also be easier for the end user to understand.

**Comment by t-schroeder** [comment]
Thanks for that information. I didn't want users to get a "New version available" prompt every time I just changed some build issues. That's why I recreated the v2.4.2 tag instead of raising the version. I think the better solution would have been to just create new tags v2.4.2a, v2.4.2b etc. for such releases. I will do that from now on. For new releases that contain actual fixes, new features etc. I will also raise the version number so that users get a notification when they open Sync-my-L2P.
